import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./reduxToolkit/provider";

export const metadata = {
  title: "Create Next Redux Toolkit App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers> 
        {/* wrapped in nextjs redux provider came with store */}
      </body>
    </html>
  );
}
